services:
  postgres:
    image: postgres:16
    container_name: aq_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - aq_pg_data:/var/lib/postgresql/data

volumes:
  aq_pg_data:
  